module OrdersHelper
  def state_select_options 
    [ 	
    	['Select a State', 'None'],
    	['Alabama', 'AL'], 
    	['Alaska', 'AK'],
    	['Arizona', 'AZ'],
    	['Arkansas', 'AR'], 
    	['California', 'CA'], 
    	['Colorado', 'CO'], 
    	['Connecticut', 'CT'], 
    	['Delaware', 'DE'], 
    	['District Of Columbia', 'DC'], 
    	['Florida', 'FL'],
    	['Georgia', 'GA'],
    	['Hawaii', 'HI'], 
    	['Idaho', 'ID'], 
    	['Illinois', 'IL'], 
    	['Indiana', 'IN'], 
    	['Iowa', 'IA'], 
    	['Kansas', 'KS'], 
    	['Kentucky', 'KY'], 
    	['Louisiana', 'LA'], 
    	['Maine', 'ME'], 
    	['Maryland', 'MD'], 
    	['Massachusetts', 'MA'], 
    	['Michigan', 'MI'], 
    	['Minnesota', 'MN'],
    	['Mississippi', 'MS'], 
    	['Missouri', 'MO'], 
    	['Montana', 'MT'], 
    	['Nebraska', 'NE'], 
    	['Nevada', 'NV'], 
    	['New Hampshire', 'NH'], 
    	['New Jersey', 'NJ'], 
    	['New Mexico', 'NM'], 
    	['New York', 'NY'], 
    	['North Carolina', 'NC'], 
    	['North Dakota', 'ND'], 
    	['Ohio', 'OH'], 
    	['Oklahoma', 'OK'], 
    	['Oregon', 'OR'], 
    	['Pennsylvania', 'PA'], 
    	['Rhode Island', 'RI'], 
    	['South Carolina', 'SC'], 
    	['South Dakota', 'SD'], 
    	['Tennessee', 'TN'], 
    	['Texas', 'TX'], 
    	['Utah', 'UT'], 
    	['Vermont', 'VT'], 
    	['Virginia', 'VA'], 
    	['Washington', 'WA'], 
    	['West Virginia', 'WV'], 
    	['Wisconsin', 'WI'], 
    	['Wyoming', 'WY'],
    	['Alberta', 'AB'],
      ['British Columbia','BC'],
      ['Manitoba','MB'],
      ['New Brunswick','NB'],
      ['Newfoundland and Labrador','NL'],
      ['Northwest Territories','NT'],
      ['Nova Scotia','NS'],
      ['Nunavut','NU'],
      ['Ontario','ON'],
      ['Prince Edward Island','PE'],
      ['Quebec','QC'],
      ['Saskatchewan','SK'],
      ['Yukon','YT']
    ]
  end
  
  # def country_select_options
  #   [ "Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
  #     "Anguilla", "Antarctica", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria",
  #     "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
  #     "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil",
  #     "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
  #     "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
  #     "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo",
  #     "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
  #     "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
  #     "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)",
  #     "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
  #     "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
  #     "Guinea-Bissau", "Guyana", "Haiti", "Heard and McDonald Islands", "Holy See (Vatican City State)",
  #     "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of", "Iraq",
  #     "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
  #     "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan",
  #     "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya",
  #     "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic Of",
  #     "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
  #     "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of",
  #     "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
  #     "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
  #     "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau",
  #     "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
  #     "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation",
  #     "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia",
  #     "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  #     "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
  #     "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
  #     "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname",
  #     "Svalbard and Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
  #     "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste",
  #     "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
  #     "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
  #     "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
  #     "Viet Nam", "Virgin Islands, British", "Virgin Islands, U.S.", "Wallis and Futuna", "Western Sahara",
  #     "Yemen", "Zambia", "Zimbabwe" ].map { |e| [e, e] }
  # end
  
  # https://www.paypal.com/en_US/ebook/PP_NVPAPI_DeveloperGuide/countrycodes_new.html
  def country_select_options
    [
      ['UNITED STATES', 'US'],
      ['AFGHANISTAN', 'AF'],
      ['ÅLAND ISLANDS', 'AX'],
      ['ALBANIA', 'AL'],
      ['ALGERIA', 'DZ'],
      ['AMERICAN SAMOA', 'AS'],
      ['ANDORRA', 'AD'],
      ['ANGOLA', 'AO'],
      ['ANGUILLA', 'AI'],
      ['ANTARCTICA', 'AQ'],
      ['ANTIGUA AND BARBUDA', 'AG'],
      ['ARGENTINA', 'AR'],
      ['ARMENIA', 'AM'],
      ['ARUBA', 'AW'],
      ['AUSTRALIA', 'AU'],
      ['AUSTRIA', 'AT'],
      ['AZERBAIJAN', 'AZ'],
      ['BAHAMAS', 'BS'],
      ['BAHRAIN', 'BH'],
      ['BANGLADESH', 'BD'],
      ['BARBADOS', 'BB'],
      ['BELARUS', 'BY'],
      ['BELGIUM', 'BE'],
      ['BELIZE', 'BZ'],
      ['BENIN', 'BJ'],
      ['BERMUDA', 'BM'],
      ['BHUTAN', 'BT'],
      ['BOLIVIA, PLURINATIONAL STATE OF', 'BO'],
      ['BOSNIA AND HERZEGOVINA', 'BA'],
      ['BOTSWANA', 'BW'],
      ['BOUVET ISLAND', 'BV'],
      ['BRAZIL', 'BR'],
      ['BRITISH INDIAN OCEAN TERRITORY', 'IO'],
      ['BRUNEI DARUSSALAM', 'BN'],
      ['BULGARIA', 'BG'],
      ['BURKINA FASO', 'BF'],
      ['BURUNDI', 'BI'],
      ['CAMBODIA', 'KH'],
      ['CAMEROON', 'CM'],
      ['CANADA', 'CA'],
      ['CAPE VERDE', 'CV'],
      ['CAYMAN ISLANDS', 'KY'],
      ['CENTRAL AFRICAN REPUBLIC', 'CF'],
      ['CHAD', 'TD'],
      ['CHILE', 'CL'],
      ['CHINA', 'CN'],
      ['CHRISTMAS ISLAND', 'CX'],
      ['COCOS (KEELING) ISLANDS', 'CC'],
      ['COLOMBIA', 'CO'],
      ['COMOROS', 'KM'],
      ['CONGO', 'CG'],
      ['CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CD'],
      ['COOK ISLANDS', 'CK'],
      ['COSTA RICA', 'CR'],
      ['CÔTE DIVOIRE', 'CI'],
      ['CROATIA', 'HR'],
      ['CUBA', 'CU'],
      ['CYPRUS', 'CY'],
      ['CZECH REPUBLIC', 'CZ'],
      ['DENMARK', 'DK'],
      ['DJIBOUTI', 'DJ'],
      ['DOMINICA', 'DM'],
      ['DOMINICAN REPUBLIC', 'DO'],
      ['ECUADOR', 'EC'],
      ['EGYPT', 'EG'],
      ['EL SALVADOR', 'SV'],
      ['EQUATORIAL GUINEA', 'GQ'],
      ['ERITREA', 'ER'],
      ['ESTONIA', 'EE'],
      ['ETHIOPIA', 'ET'],
      ['FALKLAND ISLANDS (MALVINAS)', 'FK'],
      ['FAROE ISLANDS', 'FO'],
      ['FIJI', 'FJ'],
      ['FINLAND', 'FI'],
      ['FRANCE', 'FR'],
      ['FRENCH GUIANA', 'GF'],
      ['FRENCH POLYNESIA', 'PF'],
      ['FRENCH SOUTHERN TERRITORIES', 'TF'],
      ['GABON', 'GA'],
      ['GAMBIA', 'GM'],
      ['GEORGIA', 'GE'],
      ['GERMANY', 'DE'],
      ['GHANA', 'GH'],
      ['GIBRALTAR', 'GI'],
      ['GREECE', 'GR'],
      ['GREENLAND', 'GL'],
      ['GRENADA', 'GD'],
      ['GUADELOUPE', 'GP'],
      ['GUAM', 'GU'],
      ['GUATEMALA', 'GT'],
      ['GUERNSEY', 'GG'],
      ['GUINEA', 'GN'],
      ['GUINEA-BISSAU', 'GW'],
      ['GUYANA', 'GY'],
      ['HAITI', 'HT'],
      ['HEARD ISLAND AND MCDONALD ISLANDS', 'HM'],
      ['HOLY SEE (VATICAN CITY STATE)', 'VA'],
      ['HONDURAS', 'HN'],
      ['HONG KONG', 'HK'],
      ['HUNGARY', 'HU'],
      ['ICELAND', 'IS'],
      ['INDIA', 'IN'],
      ['INDONESIA', 'ID'],
      ['IRAN, ISLAMIC REPUBLIC OF', 'IR'],
      ['IRAQ', 'IQ'],
      ['IRELAND', 'IE'],
      ['ISLE OF MAN', 'IM'],
      ['ISRAEL', 'IL'],
      ['ITALY', 'IT'],
      ['JAMAICA', 'JM'],
      ['JAPAN', 'JP'],
      ['JERSEY', 'JE'],
      ['JORDAN', 'JO'],
      ['KAZAKHSTAN', 'KZ'],
      ['KENYA', 'KE'],
      ['KIRIBATI', 'KI'],
      ['KOREA, DEMOCRATIC PEOPLES REPUBLIC OF', 'KP'],
      ['KOREA, REPUBLIC OF', 'KR'],
      ['KUWAIT', 'KW'],
      ['KYRGYZSTAN', 'KG'],
      ['LAO PEOPLES DEMOCRATIC REPUBLIC', 'LA'],
      ['LATVIA', 'LV'],
      ['LEBANON', 'LB'],
      ['LESOTHO', 'LS'],
      ['LIBERIA', 'LR'],
      ['LIBYAN ARAB JAMAHIRIYA', 'LY'],
      ['LIECHTENSTEIN', 'LI'],
      ['LITHUANIA', 'LT'],
      ['LUXEMBOURG', 'LU'],
      ['MACAO', 'MO'],
      ['MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK'],
      ['MADAGASCAR', 'MG'],
      ['MALAWI', 'MW'],
      ['MALAYSIA', 'MY'],
      ['MALDIVES', 'MV'],
      ['MALI', 'ML'],
      ['MALTA', 'MT'],
      ['MARSHALL ISLANDS', 'MH'],
      ['MARTINIQUE', 'MQ'],
      ['MAURITANIA', 'MR'],
      ['MAURITIUS', 'MU'],
      ['MAYOTTE', 'YT'],
      ['MEXICO', 'MX'],
      ['MICRONESIA, FEDERATED STATES OF', 'FM'],
      ['MOLDOVA, REPUBLIC OF', 'MD'],
      ['MONACO', 'MC'],
      ['MONGOLIA', 'MN'],
      ['MONTENEGRO', 'ME'],
      ['MONTSERRAT', 'MS'],
      ['MOROCCO', 'MA'],
      ['MOZAMBIQUE', 'MZ'],
      ['MYANMAR', 'MM'],
      ['NAMIBIA', 'NA'],
      ['NAURU', 'NR'],
      ['NEPAL', 'NP'],
      ['NETHERLANDS', 'NL'],
      ['NETHERLANDS ANTILLES', 'AN'],
      ['NEW CALEDONIA', 'NC'],
      ['NEW ZEALAND', 'NZ'],
      ['NICARAGUA', 'NI'],
      ['NIGER', 'NE'],
      ['NIGERIA', 'NG'],
      ['NIUE', 'NU'],
      ['NORFOLK ISLAND', 'NF'],
      ['NORTHERN MARIANA ISLANDS', 'MP'],
      ['NORWAY', 'NO'],
      ['OMAN', 'OM'],
      ['PAKISTAN', 'PK'],
      ['PALAU', 'PW'],
      ['PALESTINIAN TERRITORY, OCCUPIED', 'PS'],
      ['PANAMA', 'PA'],
      ['PAPUA NEW GUINEA', 'PG'],
      ['PARAGUAY', 'PY'],
      ['PERU', 'PE'],
      ['PHILIPPINES', 'PH'],
      ['PITCAIRN', 'PN'],
      ['POLAND', 'PL'],
      ['PORTUGAL', 'PT'],
      ['PUERTO RICO', 'PR'],
      ['QATAR', 'QA'],
      ['RÉUNION', 'RE'],
      ['ROMANIA', 'RO'],
      ['RUSSIAN FEDERATION', 'RU'],
      ['RWANDA', 'RW'],
      ['SAINT BARTHÉLEMY', 'BL'],
      ['SAINT HELENA', 'SH'],
      ['SAINT KITTS AND NEVIS', 'KN'],
      ['SAINT LUCIA', 'LC'],
      ['SAINT MARTIN', 'MF'],
      ['SAINT PIERRE AND MIQUELON', 'PM'],
      ['SAINT VINCENT AND THE GRENADINES', 'VC'],
      ['SAMOA', 'WS'],
      ['SAN MARINO', 'SM'],
      ['SAO TOME AND PRINCIPE', 'ST'],
      ['SAUDI ARABIA', 'SA'],
      ['SENEGAL', 'SN'],
      ['SERBIA', 'RS'],
      ['SEYCHELLES', 'SC'],
      ['SIERRA LEONE', 'SL'],
      ['SINGAPORE', 'SG'],
      ['SLOVAKIA', 'SK'],
      ['SLOVENIA', 'SI'],
      ['SOLOMON ISLANDS', 'SB'],
      ['SOMALIA', 'SO'],
      ['SOUTH AFRICA', 'ZA'],
      ['SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS'],
      ['SPAIN', 'ES'],
      ['SRI LANKA', 'LK'],
      ['SUDAN', 'SD'],
      ['SURINAME', 'SR'],
      ['SVALBARD AND JAN MAYEN', 'SJ'],
      ['SWAZILAND', 'SZ'],
      ['SWEDEN', 'SE'],
      ['SWITZERLAND', 'CH'],
      ['SYRIAN ARAB REPUBLIC', 'SY'],
      ['TAIWAN, PROVINCE OF CHINA', 'TW'],
      ['TAJIKISTAN', 'TJ'],
      ['TANZANIA, UNITED REPUBLIC OF', 'TZ'],
      ['THAILAND', 'TH'],
      ['TIMOR-LESTE', 'TL'],
      ['TOGO', 'TG'],
      ['TOKELAU', 'TK'],
      ['TONGA', 'TO'],
      ['TRINIDAD AND TOBAGO', 'TT'],
      ['TUNISIA', 'TN'],
      ['TURKEY', 'TR'],
      ['TURKMENISTAN', 'TM'],
      ['TURKS AND CAICOS ISLANDS', 'TC'],
      ['TUVALU', 'TV'],
      ['UGANDA', 'UG'],
      ['UKRAINE', 'UA'],
      ['UNITED ARAB EMIRATES', 'AE'],
      ['UNITED KINGDOM', 'GB'],
      ['UNITED STATES', 'US'],
      ['UNITED STATES MINOR OUTLYING ISLANDS', 'UM'],
      ['URUGUAY', 'UY'],
      ['UZBEKISTAN', 'UZ'],
      ['VANUATU', 'VU'],
      ['VATICAN CITY STATE', 'VA'],
      ['VENEZUELA, BOLIVARIAN REPUBLIC OF', 'VE'],
      ['VIET NAM', 'VN'],
      ['VIRGIN ISLANDS, BRITISH', 'VG'],
      ['VIRGIN ISLANDS, U.S.', 'VI'],
      ['WALLIS AND FUTUNA', 'WF'],
      ['WESTERN SAHARA', 'EH'],
      ['YEMEN', 'YE'],
      ['ZAMBIA', 'ZM'],
      ['ZIMBABWE', 'ZW']
    ]
  end
end